import React from "react";
import './Pages.css'


export default function TermsOfUse() {
    return (
        <div className="termsOfUse-wrap">
            <h1>Terms Of Use</h1>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam et pellentesque sapien, in semper ante. Duis tellus leo, fermentum id sollicitudin vitae, laoreet vel magna. Curabitur rhoncus accumsan libero. Nunc est magna, convallis nec dui eu, finibus convallis lorem. Mauris auctor dui ac neque faucibus bibendum. In sit amet gravida purus. Aliquam erat volutpat. Donec porttitor quam et velit rutrum, eget aliquet lorem placerat. Fusce convallis a dui a molestie. Aenean placerat porta orci, ut iaculis mi scelerisque quis. Etiam vel erat scelerisque, volutpat elit non, consectetur sem. Morbi sed nunc fermentum, rutrum nibh ut, maximus massa. Nunc pellentesque a ante at ullamcorper.
                <br /><br />Suspendisse tristique diam non nisi congue, a mollis libero consectetur. Morbi mattis leo vitae tempor aliquet. Integer tempor dolor non est aliquam commodo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris rhoncus lacus eget tellus condimentum varius. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean sollicitudin euismod massa a pretium. Praesent vitae velit non massa varius interdum.
                <br /><br />In egestas est non quam tincidunt rhoncus. Proin quis erat ullamcorper, dignissim neque vel, elementum augue. Vestibulum dignissim, metus quis semper vestibulum, leo velit congue quam, at volutpat massa nulla vitae nulla. Fusce sed sodales sapien. Mauris aliquam euismod leo. Cras vitae nulla facilisis neque bibendum tempus eget vel lacus. Phasellus consequat interdum mollis. Nunc rutrum massa nec sem hendrerit, suscipit consequat sapien eleifend. Sed rhoncus leo ut nulla rhoncus porttitor. Cras tempus sapien scelerisque leo efficitur tincidunt. Vivamus lectus justo, finibus lacinia diam quis, malesuada convallis lorem. Integer sit amet accumsan eros, ut efficitur ante. Aliquam augue quam, sollicitudin non ex at, dignissim pretium urna.
                <br /><br />Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Phasellus vel sodales quam, ut maximus nulla. Ut ipsum nunc, efficitur id hendrerit a, accumsan at justo. Vivamus finibus lectus vel leo tristique viverra. Nunc et posuere metus. Sed sit amet lectus quis metus gravida pellentesque. Mauris fringilla feugiat interdum. Aliquam odio orci, finibus vitae ultrices vitae, venenatis non ligula. Pellentesque ex libero, condimentum et pretium hendrerit, vehicula a enim. Nulla facilisi.
                <br /><br />Donec fermentum convallis sem, et pellentesque sapien faucibus eget. Mauris at sollicitudin augue. Praesent posuere hendrerit accumsan. Pellentesque pharetra nibh leo, eu viverra tortor pellentesque vitae. Etiam consequat lectus vitae tellus hendrerit, vitae tempor libero ultricies. Vestibulum ex neque, sodales at enim sit amet, bibendum porta metus. Aliquam erat volutpat. Praesent ut porttitor metus. Sed ut sem aliquam, lacinia massa ac, pellentesque lectus. Suspendisse potenti. Praesent sollicitudin tellus dui, ac faucibus massa posuere eu. Morbi aliquam metus diam, vitae lacinia orci finibus eget.
                <br /><br />Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam et pellentesque sapien, in semper ante. Duis tellus leo, fermentum id sollicitudin vitae, laoreet vel magna. Curabitur rhoncus accumsan libero. Nunc est magna, convallis nec dui eu, finibus convallis lorem. Mauris auctor dui ac neque faucibus bibendum. In sit amet gravida purus. Aliquam erat volutpat. Donec porttitor quam et velit rutrum, eget aliquet lorem placerat. Fusce convallis a dui a molestie. Aenean placerat porta orci, ut iaculis mi scelerisque quis. Etiam vel erat scelerisque, volutpat elit non, consectetur sem. Morbi sed nunc fermentum, rutrum nibh ut, maximus massa. Nunc pellentesque a ante at ullamcorper.
                <br /><br />Suspendisse tristique diam non nisi congue, a mollis libero consectetur. Morbi mattis leo vitae tempor aliquet. Integer tempor dolor non est aliquam commodo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris rhoncus lacus eget tellus condimentum varius. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean sollicitudin euismod massa a pretium. Praesent vitae velit non massa varius interdum.
                <br /><br />In egestas est non quam tincidunt rhoncus. Proin quis erat ullamcorper, dignissim neque vel, elementum augue. Vestibulum dignissim, metus quis semper vestibulum, leo velit congue quam, at volutpat massa nulla vitae nulla. Fusce sed sodales sapien. Mauris aliquam euismod leo. Cras vitae nulla facilisis neque bibendum tempus eget vel lacus. Phasellus consequat interdum mollis. Nunc rutrum massa nec sem hendrerit, suscipit consequat sapien eleifend. Sed rhoncus leo ut nulla rhoncus porttitor. Cras tempus sapien scelerisque leo efficitur tincidunt. Vivamus lectus justo, finibus lacinia diam quis, malesuada convallis lorem. Integer sit amet accumsan eros, ut efficitur ante. Aliquam augue quam, sollicitudin non ex at, dignissim pretium urna.
                <br /><br />Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Phasellus vel sodales quam, ut maximus nulla. Ut ipsum nunc, efficitur id hendrerit a, accumsan at justo. Vivamus finibus lectus vel leo tristique viverra. Nunc et posuere metus. Sed sit amet lectus quis metus gravida pellentesque. Mauris fringilla feugiat interdum. Aliquam odio orci, finibus vitae ultrices vitae, venenatis non ligula. Pellentesque ex libero, condimentum et pretium hendrerit, vehicula a enim. Nulla facilisi.
                <br /><br />Donec fermentum convallis sem, et pellentesque sapien faucibus eget. Mauris at sollicitudin augue. Praesent posuere hendrerit accumsan. Pellentesque pharetra nibh leo, eu viverra tortor pellentesque vitae. Etiam consequat lectus vitae tellus hendrerit, vitae tempor libero ultricies. Vestibulum ex neque, sodales at enim sit amet, bibendum porta metus. Aliquam erat volutpat. Praesent ut porttitor metus. Sed ut sem aliquam, lacinia massa ac, pellentesque lectus. Suspendisse potenti. Praesent sollicitudin tellus dui, ac faucibus massa posuere eu. Morbi aliquam metus diam, vitae lacinia orci finibus eget.
            </p>
        </div>
    )
}